### ISSUE TITLE
[FEATURE] <clearer power up descriptions>

### ISSUE THREAD

**Issue by RootBible1** [Fruktus/QuadradiusPreservationProject#114]
### Was this feature present in original?

- [ ] This feature was present in original
- [ ] This feature is new

### Target platform

Online Version

### Describe the request

I am having trouble understanding what some of the power ups do.

### Additional information

if you could fix this it would really be helpful.

**Comment by RootBible1** [comment]
if there is a downloadable cheat sheet that would be amazing!

**Comment by Fruktus** [comment]
Hi! Thanks for reporting. The original had a website explaining everything in detail (and some additional assets). This list is by far the most requested addition. I can't make the buttons in-game work at the moment (I hope that with Ruffle's progression this will become possible), but I'll add the link on the webpage to the manual for now, it should be available soon.

**Comment by Fruktus** [comment]
I've added the list, it's linked on the main page and you can see it [here](https://quadradius.ddns.net/directions.html)

**Comment by RootBible1** [comment]
Thank you! I love this game!
