### ISSUE TITLE
[BUG] <power ups>

### ISSUE THREAD

**Issue by RootBible1** [Fruktus/QuadradiusPreservationProject#116]
### Affected platform

Online Version

### Describe the bug

you said on your power up sheet that you were going to release a new power up every first Tuesday of the month are you still doing that?
![Screen Shot 2024-09-03 at 10 04 33 AM](https://github.com/user-attachments/assets/c6dedaf6-3a1a-4e0f-9e85-62963182032a)

### Expected behavior

I was expected a new power up to come out but I did not see anything new.

### Additional information

I just wanted to check in to see if that was happening.

**Comment by Fruktus** [comment]
Hi. I know that I didn't mention it but this is the original page that was present in 2007, it was not created by me. I am not planning on modifying the game in any way, aside from re-adding the functionality that it originally had, such as this guide.
