### ISSUE TITLE
[BUG] Scoreboard

### ISSUE THREAD

**Issue by RootBible1** [Fruktus/QuadradiusPreservationProject#117]
### Affected platform

Launcher

### Describe the bug

I don't really understand the score board ranking system on the power up sheet and I also don't think it is working right. ![Screen Shot 2024-09-03 at 10 14 56 AM](https://github.com/user-attachments/assets/b94ec65c-83e1-479f-8ef0-607f60c57d26)

### Expected behavior

I have won more than once and I don't think its adding up my score correctly.

### Additional information

I don't know if I am doing something wrong but i just want to make sure.

**Comment by Fruktus** [comment]
Yes, this system is currently not working. We have an open issue for this here: #43. There is no ETA for now.

**Comment by Fruktus** [comment]
As for the manual on how this mechanism works, I'll probably prepare some description once the ranking will work.
