### ISSUE TITLE
Lost membership feature

### ISSUE THREAD

**Issue by BucketsN** [Fruktus/QuadradiusPreservationProject#143]
### Affected platform

Launcher

### Describe the bug

I'm so delighted this game is back,. Thank you.
Is there a way to play this game as a member - I was playing as a member up to yesterday, but now I"m just getting told that my password is incorrect.

### Expected behavior

I'd love to get the feature back. And I'd be happy to pay a member ship fee.

### Additional information

That's all - thanks

**Comment by Fruktus** [comment]
Hi! Thanks for the report.

This is not a bug - we are in the process of introducing registration feature, which will allow you to set passwords for accounts. Yesterday we have re-enabled the password verification.

I will update the READMEs shortly.

This change allows players to fully own their wins and scores, ensuring that they are tied to your account alone.

We are posting updates about such changes in our [Discord server](https://discord.gg/cVkV8pah4d) in which you can register by using our bot. 

Best regards

**Comment by Fruktus** [comment]
FYI the prompt that password is incorrect is shown both when the password is actually incorrect and when the username you're using does not exist yet.
