### ISSUE TITLE
Can you please give a clearer explanation of how to install (i'm an idiot when it comes to python im sorry)

### ISSUE THREAD

**Issue by TheLemon27** [Fruktus/QuadradiusPreservationProject#25]
I know little to nothing about how to installing python software so can you tell me how? (sorry im an idiot)

**Comment by kjarosh** [comment]
Do you have an issue with installing Python itself or rather the QRServer? In other words: are you able to execute the Python interpreter from the terminal?

Also, what OS are you using?

**Comment by Fruktus** [comment]
Hi, you can checkout this video if you are on windows https://www.youtube.com/watch?v=5tOmdtZ6U4I. Let me know if you have trouble.
