### ISSUE TITLE
[BUG] New opponent bugs out, duplicate lobby joins

### ISSUE THREAD

**Issue by Fruktus** [Fruktus/QuadradiusPreservationProject#66]
## **Platform**
- [ ] Website player
- [ ] Launcher
- [x] Server

```v1.1.0```

## **Describe the bug**

When playing match and clicking ```new opponent``` the lobby is rejoined, but with duplicate usernames, and starting match with them breaks the game.

Possibly related to broken play again

## **Steps To Reproduce**

- start a match with two instances
- resign
- click play again

**Comment by kjarosh** [comment]
Should work now
